### ISSUE TITLE
Fedora RPM

### ISSUE THREAD

**Issue by martinoj2009** [mmstick/systemd-manager#18]
Is there any plans for a Fedora RPM?

**Comment by mmstick** [comment]
I don't use Fedora so I can't provide a RPM. If anyone's willing to package for Fedora, they are free to do so. The only issue is that Fedora does not yet provide the Rust programming language in their software repository due to Red Hat policies regarding how Rust is packaged (main reason why I don't use Fedora), but that Red Hat is working on attempting to remedy that soon.

I don't think that would stop you from packaging your own RPM though as Rust binaries are statically-compiled by default and thus do not need a dynamic Rust standard library as a dependency (although you can package your Rust software like that if you wish). The only dependency is GTK3.

**Comment by mmstick** [comment]
https://github.com/mmstick/systemd-manager/commit/dc38ff71670e2b901eeb0b80df57bfbb92bebbf7
