### ISSUE TITLE
Provide a i386 package for Ubuntu

### ISSUE THREAD

**Issue by khurshid-alam** [mmstick/systemd-manager#21]
I can only download amd64 from release. I need an i386 package(deb).

**Comment by mmstick** [comment]
You're free to compile it yourself. Installing Rust applications is painless. The provided deb is ancient compared to git head.

**Comment by khurshid-alam** [comment]
@mmstick Compiling a application after every update is not what I intend to do. Do you have any plans to create a Ubuntu-PPA?

**Comment by mmstick** [comment]
I do not use Ubuntu or Debian, and therefore I do not intend to create an Ubuntu PPA at this time. I do not particularly like Ubuntu's PPAs or the Debian packaging format, which are both convoluted processes. I will leave it up to someone else to offer a PPA if they choose to do so. I would have provided a Snappy package, but Canonical's Snappy format is a complete mess, doesn't support Rust, and will not work with applications that require PolicyKit. Likewise, as I do not use Fedora or any other RPM-based distributions, I will not be providing any RPMs or RPM repositories any time soon.

At the very least, I have been long providing an option in my Makefile that will automatically compile, package for Debian systems, and install it into the system, just by executing `make ubuntu`. All platforms supported by both Rust and GTK3 should be able to generate the packages, and do so in a matter of mere seconds. Then, you can choose to either never update the application, or occasionally execute `git pull && make ubuntu` to automatically update it.

There is no need to update the application unless you decide you want any updates that I push. Any updates that I push are not for the purpose of fixing errors but improving the quality of the source code or adding new features. By improving the quality of the source code, I primarily mean that I am always actively working on improving the readability of the code so that others may have a practical example to learn Rust from, or improving the performance the performance of the existing code with a few optimizations here and there, such as the following change:

```rust
// Initialize a String with the capacity of the file obtained from
// the file's metadata, and then read the contents of the file
// into the string. Return an empty String if it fails.
let capacity = file.metadata().map(|x| x.len()).unwrap_or(0) as usize;
let mut output = String::with_capacity(capacity);
file.read_to_string(&mut output).map(|_| output).ok().unwrap_or_default()
```

As this is a Rust application developed safely, there will never be any 'dealing with errors' that are common with software written in other languages. I always execute `cargo test` and `cargo clippy` before pushing any changes to the master, in addition to testing it out in practice. The Rust compiler has very power static code analysis that makes it incredibly hard to offer software that has errors, and so I doubt you'll ever find an error that isn't intended behaviour.

With each update, I have eliminated more and more instances of `unwrap()` in the source code and thus have eliminated practically all usage of `unwrap()`. The only places that still have `unwrap()` are used in places that cannot fail within reason, such as assuming that all systems running this application have systemd installed. You would be far more likely to have bugs in your distribution's version of GTK3 that causes errors than you would with this Rust software.

**Comment by daboross** [comment]
I don't think rust is entirely that immune to bugs - one of the main things to consider is dependency updates, which may be using unsafe code and/or rustc updates. It won't be as common, no, but important security updates do happen.

I don't use ubuntu or debian myself, but I'm 90% sure I can build deb packages successfully on this computer and I can do that for release versions if that would be helpful! I don't know much about maintaining a PPA though.

**Comment by mmstick** [comment]
Dependency updates aren't a concern because they are statically linked into the binary at compile time, and because I am shipping the Cargo.lock file as well, anyone who builds this application will build with the exact same dependency versions. I do not push commits to update the Cargo.lock and Cargo.toml files without thoroughly testing every codepath anyway. The Cargo.lock file not only ensures that everyone who compiles the software is locked to the same version from Crates.io, but that even Git repositories are locked to the same commit.

Updates to rustc don't cause errors or bugs. Any breaking changes to the standard library API are reported as warnings by the compiler two or three releases in advance before making them compiler errors, which gives me plenty of time to update the code in advance. I develop with Rust Nightly so I have at least 24 weeks in advance to make changes to the code if there is an API breakage, which has happened effectively never ever since Rust 1.0 released. I also will not update a dependency without fixing any breakage in the API of those libraries.

Unsafe code isn't a bad thing, as it's useful to take advantage of the unsafe aspect of Rust to gain performance benefits when you can guarantee that it will not cause any issues. I used a few unsafe blocks to escape bounds checking of a few indexes and I can stand behind their usage as being safe. The only thing you have to worry about is bugs and security issues in C libraries that are being linked to, which in this case is GTK3 specifically. Rust applications do not need to be updated every time a C library updates, because C libraries are linked dynamically. If you get an update for GTK in your distribution, then this application will be using the updated version you installed without needing a recompile.

And finally, as for security bugs related to Rust software specifically, that is a non-issue because Rust does not allow any of the unsafe behaviour that security bugs exploit, at least not without using unsafe to start writing Assembly and linking to external C libraries. There has yet to be an incident where a Rust library was found to be vulnerable to a security bug, and the Crates website is capable of automatically sending an email out to all the developers who are using a vulnerable version, if that ever happens.

**Comment by daboross** [comment]
@mmstick With dependencies, that is literally what I'm talking about - all dependency versions are frozen when compiled. If there's an exploit discovered in a dependency which uses unsafe code, the only way to fix it is to get a new version of systemd-manager.

Rust is less prone to security bugs, but memory-safety isn't the only thing that causes exploits. Also, systemd-manager has dependencies (gtk-rs, etc.), which literally do use unsafe code and link to external C libraries in this program. It's not likely, but it's a complete possibility that an upgrade to systemd-manager will be required for security purposes.

I'm not really trying to refute your point entirely, but rust isn't a magic bullet. I use it, and love it, but I don't think it's reasonable to say that the only reason you'd ever upgrade is for new features.

**Comment by mmstick** [comment]
@daboross `gtk-rs` isn't a concern because C libraries are dynamically linked. Any update to GTK does not require an update to a GTK-dependent application.

**Comment by daboross** [comment]
@mmstick Yes, but if there's a bug in unsafe gtk-rs code which causes a security concern, that would require an upgrade. I'm just trying to say that it's possible for any program, even ones written in rust, to have bugs which would require upgrading.

**Comment by khurshid-alam** [comment]
@mmstick I can help creating a PPA. But first we need to create a proper debian packaging. I noticed there is a single control file under debian/debian in your source tree. It would make things easy for me if you can create those other files....specially `debian/copyright`.

https://www.debian.org/doc/manuals/debmake-doc/ch04.en.html

**Comment by mmstick** [comment]
I have added the [copyright file](https://github.com/mmstick/systemd-manager/commit/d9600947d193cd71f979621358bf873e7a3f9739).
