### ISSUE TITLE
Missing Gnome 3.14 support ?

### ISSUE THREAD

**Issue by ivoarch** [mmstick/systemd-manager#34]
Hi,  is it possible to add support for Gnome 3.14/CentOS 7 ?

```
--- stderr
`"pkg-config" "--libs" "--cflags" "gdk-3.0 >= 3.16"` did not exit successfully: exit code: 1
--- stdout
Requested 'gdk-3.0 >= 3.16' but version of GDK is 3.14.13
```

**Comment by mmstick** [comment]
3.16 is required, so I won't be supporting anything earlier than that. All recent Linux distributions have long since updated from 3.14. CentOS is probably best off without using a GUI for management. I have yet to provide SSH support as I'm working on a lot of other Rust-related projects right now, but I do accept pull requests.
